### PR TITLE
Update on 2016-08-18

### PR DESCRIPTION
**Pull request by jollygoodbot**

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
@winston change to commit to master directly?

**Comment by winston** [comment]
@JuanitoFatas `master`? But this is for github pages right?

**Comment by JuanitoFatas** [comment]
> @JuanitoFatas master? But this is for github pages right?

Ah I mean the bot commit to gh-pages directly without opening a PR.

**Comment by winston** [comment]
Yes. We can do that!

**Comment by JuanitoFatas** [comment]
> Yes. We can do that!

Ok will do.

**Comment by winston** [comment]
🙇

**Comment by JuanitoFatas** [comment]
@winston done and fyi https://github.com/jollygoodcode/data.rubyasia.com/commit/71b12becc0f34ed5d8fd3c263956f84fc06cb48c

**Comment by winston** [comment]
Thank you @JuanitoFatas!

**Pull request merged**
